# Site settings
title_left    : "Dalcy"
title_right   : "Think" # default: ""
description   : "Dalcy's writing blog."
keywords      : "Dalcy, thinkSpace, blog, Android, Developer"
url           : https://dalcyyuni.github.io/blog/ # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Dalcy Park"
  job      : "개발자"
  email    : springfevernme@gmail.com
  url      : http://dalcyyuni.github.io/blog/
  github   : http://github.com/dalcyyuni
  instagram : dalcyyuni
plugins:
  - bourbon
  - jekyll-paginate
  - jekyll-sitemap

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
disqus_url : https-dalcyyuni-github-io-blog-1.disqus.com
disqus_id : disqus_YZ76D22AF5
